### ISSUE TITLE
Fix sometimes our script throws error while scrolling down while clearing all chats

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#89]
It is happing most probably due to our script getting the options button from the previous chat and then the next chat loaded but we are trying to click on an element from the previous chat's button

So, to fix it we need to use the `_wait_for_an_element_to_deattached` for the options button from the previous chat

Following error 
```python
Traceback (most recent call last):
  File "E:\ee\tithiwa\tithiwa\temp\test.py", line 41, in <module>
    tithiwabot.clear_all_chats()
  File "E:\ee\tithiwa\tithiwa\chatroom.py", line 71, in clear_all_chats
    self._wait_for_presence_of_an_element(SELECTORS.CHATROOM__OPTIONS).click()
 ..etc
  File "C:\Users\ee\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=95.0.4638.69)
```

**Comment by fabestah** [comment]
Hello there!
I would like to work on that issue as my first real issue here on GitHub if that's okay with you? 😊 (I've learned Python and Selenium, jfyi)
Additionally, I would like to know if this project is actually still being developed / maintained by you?
